project:
  type: book

book:
  title: "Profit Analytics for Entrepreneurs"
  author: "Nile Hatch"
  date: "1/1/2025"
  
  navbar:
    background: primary
    search: true
  reader-mode: true

#  page-footer:
#    left: |
#      _Expeditionary Innovation_ was written by Nile Hatch.
#    right: |
#      This book was built with <a href="https://quarto.org/">Quarto</a>.
# cover-image: cassia_crossbill_2.jpg
#  site-url: https://ei.nilehatch.com/
#  repo-url: https://github.com/nilehatch/exp_innov/
#  page-navigation: true
#  bread-crumbs: true
#  search: true

  
  chapters:
    - index.qmd
    - intro.qmd
    - part: Uncertainty
      chapters:
        - uncertainty_entrepreneurship.qmd
        - uncertainty_profit.qmd
    - part: Profit
      chapters:
        - demand.qmd
        - durable_demand.qmd
        - nondurable_demand.qmd
        - cost.qmd
        - cost_dynamics.qmd
        - profit.qmd
    - part: Competition
      chapters:
        - competition.qmd
        - entry.qmd
        - competitive_advantage.qmd
        - non-price_competition.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    number-depth: 2
    css: custom.css

#  pdf:
#    documentclass: scrreprt

editor: source

execute:
  echo: false
  warning: false
  error: false
  setup: |
    library(tidyverse)
    library(scales)
    library(ggthemes)
    library(gt)
    library(janitor)
    library(vroom)
    library(readxl)
    library(here)
    library(plotly)  