project:
  type: book
  output-dir: _book

book:
  title: "Is This Worth Doing?"
  subtitle: "How to Evaluate Profit Before Revenue Exists"
#  author: "Nile Hatch"
#  date: "1/1/2026"
  
  navbar:
    background: primary
    search: true
  reader-mode: true

  page-footer:
    left: |
      _Is This Worth Doing?_ was written by Nile Hatch (2026).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
# cover-image: 
  site-url: https://ei.nilehatch.com/
  repo-url: https://github.com/nilehatch/exp_innov/
  page-navigation: true
  bread-crumbs: true
  search: true

  
  chapters:
    - index.qmd
    - part: The Decision and the Object
      chapters:
        - ch1_is_this_worth_doing.qmd
        - ch2_uncertainty_types.qmd
        - ch3_profit_before_revenue.qmd    
#    - intro.qmd
    - part: Uncertainty
      chapters:
        - uncertainty_entrepreneurship.qmd
        - uncertainty_profit.qmd
    - part: Demand
      chapters:
        - demand.qmd
        - durable_demand.qmd
        - nondurable_demand.qmd
    - part: Profit
      chapters:
        - cost.qmd
        - cost_dynamics.qmd
        - profit.qmd
    - part: Competition
      chapters:
        - competition.qmd
        - competition_undiff_bertrand.qmd
        - competition_diff_bertrand.qmd        
        - competitive_advantage.qmd
        - entry.qmd        
    - part: part_competitive_dynamics.qmd
      chapters:
        - game_theory.qmd
        - simultaneous_games.qmd        
        - sequential_games.qmd
        - strategic_commitment.qmd
    - part: Competing to Sell to Businesses
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    number-depth: 2
    css: custom.css

#  pdf:
#    documentclass: scrreprt

editor: source

execute:
  echo: false
  warning: false
  error: false
  setup: |
    library(tidyverse)
    library(scales)
    library(ggthemes)
    library(gt)
    library(janitor)
    library(vroom)
    library(readxl)
    library(here)
    library(plotly)  