project:
  type: book
  output-dir: _book

book:
  title: "Is This Worth Doing?"
  subtitle: "How to Evaluate Profit Before Revenue Exists"  
#  author: "Nile Hatch"  
#  date: "1/1/2026"
  reader-mode: true
  site-url: https://ei.nilehatch.com/
  repo-url: https://github.com/nilehatch/exp_innov/

  page-footer:
    left: |
       _Is This Worth Doing?_ was written by Nile Hatch (2026).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  sidebar:
    style: "docked"   # or "floating"
    collapse-level: 1
    

## from ent analytics version
#  navbar:
#    background: primary
#    search: true
#  reader-mode: true

  page-navigation: true
  bread-crumbs: true
  search: true

  
  chapters:
    - index.qmd
    - part: The Pre-Revenue Decision
      chapters:
        - ch1_is_this_worth_doing.qmd
        - ch2_uncertainty_types.qmd
        - ch3_profit_before_revenue.qmd
        - ch4_need_to_know.qmd

    - part: Learning Demand
      chapters:
        - ch5_demand.qmd
        - ch6_design_experiment.qmd
        - ch7_execute_experiment.qmd
        - ch8_estimate_demand.qmd

    - part: part_demand_toolkits.qmd # Toolkit
      chapters:
        - tk1_frame_problem.qmd
        - tk2_survey_design.qmd
        - tk3_validate_data.qmd
        - tk4_preparing_data.qmd
        - tk5_estimated_demand_check.qmd
        
    - part: part_cost_profit.qmd
      chapters:
        - ch9_cost.qmd
        - ch10_scale.qmd
        - ch11_profit.qmd
        - ch12_profit_reasoning.qmd

    - part: part_profit_toolkits.qmd # Toolkit
      chapters:
        - tk1_frame_problem.qmd
        
    - part: Old Econ Profit
      chapters:
#        - cost.qmd
        - cost_dynamics.qmd
        - profit.qmd
    - part: Competition
      chapters:
        - competition.qmd
        - competition_undiff_bertrand.qmd
        - competition_diff_bertrand.qmd        
        - competitive_advantage.qmd
        - entry.qmd        
    - part: part_competitive_dynamics.qmd
      chapters:
        - game_theory.qmd
        - simultaneous_games.qmd        
        - sequential_games.qmd
        - strategic_commitment.qmd
    - part: Competing to Sell to Businesses
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#    include-after-body: collapse-parts.html
    css:
      - base.css
      - custom_itwd.css
    number-sections: true
    number-depth: 2
    fig-cap-location: margin
    tbl-cap-location: margin
#    embed-resources: true

editor: source

execute:
  echo: false
  warning: false
  error: false